## Going to learn about:

1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

- Pandas is an open-source library in Python that is made mainly for working with relational or labeled data both easily and intuitively

- Pandas is mostly used for data analysis tasks in Python.

- Pandas is a data manipulation package in Python for tabular data., whereas the NumPy module works with the numerical data.

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(0,28).reshape(7,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [3]:
# Creating Dataframe
df= pd.DataFrame(data = np.arange(0,28).reshape(7,4), index = ["Row1","Row2","Row3","Row4","Row5","Row6","Row7"], columns = ["Column1","Column2","Column3","Column4"])

In [4]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [5]:
df.tail()

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
Row6       20       21       22       23
Row7       24       25       26       27

In [6]:
df.head(7)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
Row6       20       21       22       23
Row7       24       25       26       27

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Row1 to Row7
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  7 non-null      int32
 1   Column2  7 non-null      int32
 2   Column3  7 non-null      int32
 3   Column4  7 non-null      int32
dtypes: int32(4)
memory usage: 168.0+ bytes


In [9]:
df.describe() # Columns must be integer or float

Column1    Column2    Column3    Column4
count   7.000000   7.000000   7.000000   7.000000
mean   12.000000  13.000000  14.000000  15.000000
std     8.640988   8.640988   8.640988   8.640988
min     0.000000   1.000000   2.000000   3.000000
25%     6.000000   7.000000   8.000000   9.000000
50%    12.000000  13.000000  14.000000  15.000000
75%    18.000000  19.000000  20.000000  21.000000
max    24.000000  25.000000  26.000000  27.000000

## Indexing

- Indexing can be done by these three ways
- Columnname, rowindex[loc], rowindex or columnindex number[.iloc]

In [10]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

- By using column name

In [11]:
# By using column name
df[['Column1','Column2','Column3']] # if you have multiple column then you have to define list in multinested list.

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18
Row6       20       21       22
Row7       24       25       26

In [12]:
type(df[['Column1','Column2','Column3']]) # This is DataFrame

pandas.core.frame.DataFrame

In [13]:
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Row6    20
Row7    24
Name: Column1, dtype: int32

## Series

In [14]:
type(df['Column1']) # This is series

pandas.core.series.Series

- DataFrame is the combination of multiple rows and columns whereas Series is single row or column.

In [15]:
df.loc['Row3']

Column1     8
Column2     9
Column3    10
Column4    11
Name: Row3, dtype: int32

- rowindex[loc]

In [16]:
type(df.loc['Row3'])

pandas.core.series.Series

In [17]:
df.loc[:,['Column1','Column4']]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19
Row6       20       23
Row7       24       27

In [18]:
df.loc[['Row2','Row3']]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11

- rowindex or columnindex number[.iloc]

In [19]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [20]:
df.iloc[1:3,0:2 ] # I need 4 5 8 9

Column1  Column2
Row2        4        5
Row3        8        9

In [21]:
df.iloc[0:5,3:4]

Column4
Row1        3
Row2        7
Row3       11
Row4       15
Row5       19

In [22]:
df.iloc[:,[0,3]]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19
Row6       20       23
Row7       24       27

In [23]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19
Row6       21       22       23
Row7       25       26       27

- Converting dataframe into arrays

In [24]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23],
       [25, 26, 27]])

## Basic Operation

In [25]:
df.isnull().sum() # If the value is not null then it add 0 to it

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [26]:
df1 = pd.DataFrame(data = [[1,np.nan,2],[1,3,4]], index = ["Row1","Row2"], columns = ["Column1","Column2","Column3"])

In [27]:
df1

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [28]:
df1.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [29]:
df1.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [30]:
df1.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [31]:
df["Column1"].value_counts()

0     1
4     1
8     1
12    1
16    1
20    1
24    1
Name: Column1, dtype: int64

In [32]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [33]:
df['Column3'].unique() # Here all the values are unique.

array([ 2,  6, 10, 14, 18, 22, 26])

In [34]:
df >2

Column1  Column2  Column3  Column4
Row1    False    False    False     True
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row5     True     True     True     True
Row6     True     True     True     True
Row7     True     True     True     True

In [35]:
df['Column2']>2

Row1    False
Row2     True
Row3     True
Row4     True
Row5     True
Row6     True
Row7     True
Name: Column2, dtype: bool

In [36]:
df[df['Column2']>2] # Conditional Indexing

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
Row6       20       21       22       23
Row7       24       25       26       27

4. StringIO
5. Pandas read_csv

## Reading different Data Sources with the help of pandas

In [37]:
from io import StringIO # Inmemory File Object

In [38]:
df = pd.read_csv('mercedesbenz.csv') # if the files are read it converts into DataFrame and while reading, read_csv convert the file into StringIO formate

In [39]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [40]:
type(df)

pandas.core.frame.DataFrame

In [41]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'c,d,3')

In [42]:
type(data)

str

In [43]:
## in memory file format object
StringIO(data)

In [44]:
pd.read_csv(StringIO(data)) #read_csv need file formated data

col1 col2  col3
0    x    y     1
1    c    d     3

In [45]:
import pandas as pd
df2 = pd.read_csv('mercedesbenz.csv', usecols = ['X0','X1','X2','X3','X4','X5'])
df2.head()

X0 X1  X2 X3 X4 X5
0   k  v  at  a  d  u
1   k  t  av  e  d  y
2  az  w   n  c  d  x
3  az  t   n  f  d  x
4  az  v   n  f  d  h

In [46]:
df.to_csv('test.csv',index=False)

## Datatypes in CSV

In [47]:
data = ('a,b,c,d\n''1,2,3,4\n''5,6,7,8\n''9,10,11')

In [48]:
df3=pd.read_csv(StringIO(data))

In [49]:
df3

a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [50]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int64  
 1   b       3 non-null      int64  
 2   c       3 non-null      int64  
 3   d       2 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 224.0 bytes


In [51]:
df3 = pd.read_csv(StringIO(data), dtype = 'object')

In [52]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       2 non-null      object
dtypes: object(4)
memory usage: 224.0+ bytes


In [53]:
df3.head()

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [54]:
df3.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [55]:
df3['a'][0]

'1'

In [56]:
data = ('a,b,c,d\n''1,2,3,4\n''5,6,7,8\n''9,10,11')

In [57]:
df = pd.read_csv(StringIO(data), dtype = {'a':int,'b':float,'c':int})

In [58]:
df


a     b   c    d
0  1   2.0   3  4.0
1  5   6.0   7  8.0
2  9  10.0  11  NaN

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int32  
 1   b       3 non-null      float64
 2   c       3 non-null      int32  
 3   d       2 non-null      float64
dtypes: float64(2), int32(2)
memory usage: 200.0 bytes


In [60]:
df.dtypes

a      int32
b    float64
c      int32
d    float64
dtype: object

In [61]:
data = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')

In [62]:
pd.read_csv(StringIO(data))

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [63]:
pd.read_csv(StringIO(data), index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [64]:
# Use index cols and usecols
data = ('a,b,c\n'
        '4,apple,bat\n'
        '8,orange,cow')

In [65]:
pd.read_csv(StringIO(data), usecols=['a','b','c'], index_col=0)

b    c
a             
4   apple  bat
8  orange  cow

In [66]:
import pandas as pd

data = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item', sep='\t')


HTTPError: HTTP Error 403: Forbidden