# Difference Between NumPy Array and List in Python

- Data type storage
- Importing module
- Numerical operation
- Modification capabilities
- Consumes less memory
- Fast as compared to the python list
- Convenient to use

In [1]:
%timeit [j**4 for j in range(1,9)]

2.37 µs ± 56.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
import numpy as np

In [3]:
%timeit np.arange(1,9)

594 ns ± 52.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## NumPy Array

In [4]:
x = [1,2,3,4]
    
y = np.array([1,2,3,4])

print(type(x))
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
l = []

for i in range(1,5):
    int_1 = int(input("Enter: "))
    l.append(int_1)
print(np.array(l))

Enter: 4
Enter: 5
Enter: 6
Enter: 7
[4 5 6 7]


### Dimension in Arrays

1. 1-D Array
2. 2-D Array
3. 3-D Array
4. Higher Dimensional Array

### To check the dimension of Array

In [6]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print("Dimension of array is",ar2.ndim,"- D Array")

[[1 2 3 4]
 [5 6 7 8]]
Dimension of array is 2 - D Array


In [7]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print("Dimension of array is",ar3.ndim,"- D Array")

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Dimension of array is 3 - D Array


In [8]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Creating array of Zero

In [9]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones

In [10]:
ar_one = np.ones(5)

In [11]:
print(ar_one)

[1. 1. 1. 1. 1.]


## Creating empty array

In [12]:
ar_empty = np.empty(4)
print(ar_empty) # Contain the value of previous memory

[0. 0. 0. 0.]


## Range

In [13]:
ar_rn = np.arange(5)
print(ar_rn)

[0 1 2 3 4]


## Diagonal element filled with 1's

In [14]:
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
ar_dia1 = np.eye(3,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Linspace

In [16]:
ar_lin = np.linspace(0,20,num=5) # Array with gaps
print(ar_lin)

[ 0.  5. 10. 15. 20.]


## Creating NumPy Arrays with Random Numbers

### Rand() - This function is used to generate random value between 0 to 1.

In [17]:
var = np.random.rand(4) # random num between 0 to 1

In [18]:
print(var)

[0.18907734 0.52218797 0.14093473 0.4518354 ]


In [19]:
var1 = np.random.rand(2,3)
print(var1)

[[0.16642582 0.79944208 0.37028697]
 [0.48150025 0.15181124 0.96249682]]


### Randn() - Generate random value close to zero, may return +ve or -ve as well.

In [20]:
var2 = np.random.randn(5)

print(var2)

[ 0.02860159 -0.09408098 -2.04125277 -0.45841631 -0.34229711]


### ranf()

In [21]:
var3 = np.random.ranf(4) # [0.0,1.0)
print(var3)

[0.90093458 0.3748264  0.91533804 0.15802037]


### randint()

In [22]:
#var4 = np.random.randint(min,max,total_values)
var4 = np.random.randint(5,20,5)
print(var4)

[15 16  9 13 16]


## Data Types in NumPy Arrays

In [23]:
var = np.array([1,2,3])
print("Data Type: ",var.dtype)

Data Type:  int32


In [24]:
var = np.array([1.4,2.5,3.2])
print("Data Type: ",var.dtype)

Data Type:  float64


In [25]:
var = np.array(["2","f"])
print("Data Type: ",var.dtype) #String Datatype

Data Type:  <U1


In [26]:
var = np.array(["c","f"])
print("Data Type: ",var.dtype)

Data Type:  <U1


### Converting the datatype

In [27]:
x = np.array([1,2,3])
print("Data Type: ",x.dtype)

Data Type:  int32


In [28]:
x = np.array([1,2,3], dtype=np.int8)
print("Data Type: ",x.dtype)
print(x)

Data Type:  int8
[1 2 3]


In [29]:
x1 = np.array([1,2,3], dtype="f")
print("Data Type: ",x1.dtype)
print(x1)

Data Type:  float32
[1. 2. 3.]


In [30]:
x2 = np.array([1,2,3])  #Using as a function

new = np.float32(x2)

print("Data Type: ",x2.dtype)
print("Data Type: ",new.dtype)

print(x2)
print(new)

Data Type:  int32
Data Type:  float32
[1 2 3]
[1. 2. 3.]


In [31]:
x2 = np.array([1,2,3])  #Using as a function

new = np.float32(x2)

new_one = np.int_(new)

print("Data Type: ",x2.dtype)
print("Data Type: ",new.dtype)
print("Data Type: ",new_one.dtype)

print(x2)
print(new)
print(new_one)

Data Type:  int32
Data Type:  float32
Data Type:  int32
[1 2 3]
[1. 2. 3.]
[1 2 3]


In [32]:
x3 = np.array([1,2,3,4,5])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


## Arithmetic Operation

In [33]:
var = np.array([1,2,3,4])

varadd = var+3

print(varadd)

[4 5 6 7]


In [34]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,3)

print(varadd)

[4 5 6 7]


In [35]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1+var2

print(varadd)

[2 4 6 8]


In [36]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)

print(varadd)

[2 4 6 8]


In [37]:
var = np.array([1,2,3,4])

varadd = var-3

print(varadd)

[-2 -1  0  1]


In [38]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1*var2

print(varadd)

[ 1  4  9 16]


In [39]:
var1 = np.array([4,6,1,2])
var2 = np.array([1,2,3,4])

varadd = var1/var2

print(varadd)

[4.         3.         0.33333333 0.5       ]


In [40]:
var1 = np.array([4,6,1,2])
var2 = np.array([1,2,3,4])

varadd = var1%var2

print(varadd)

[0 0 1 2]


In [41]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1**var2 #Power

print(varadd)

[  1   4  27 256]


In [42]:
var1 = np.array([4,6,1,2])


varadd = np.reciprocal(var1) #1/a

print(varadd)

[0 0 1 0]


### 2-D Array

In [43]:
var1 = np.array([[4,6,1,2],[3,2,6,7]])

var2 = var1%3

print(var2)

[[1 0 1 2]
 [0 2 0 1]]


In [44]:
var1 = np.array([[4,6,1,2],[3,2,6,7]])
var2 = np.array([[6,7,8,9],[3,2,0,7]])

print(var1)
print()
print(var2)
print()
varadd = var1+var2

print(varadd)

[[4 6 1 2]
 [3 2 6 7]]

[[6 7 8 9]
 [3 2 0 7]]

[[10 13  9 11]
 [ 6  4  6 14]]


## Arithmetic Functions

In [45]:
var = np.array([5,8,2,3,4])

print("Minimum :",np.min(var),"Index : ",np.argmin(var))
print("Maximum :",np.max(var),"Index :",np.argmax(var))

Minimum : 2 Index :  2
Maximum : 8 Index : 1


In [46]:
var = np.array([[5,8,2,3],[0,6,7,10]])  # Axis =0 "Col", # Axis =1 "Row"
print(np.min(var,axis=1))

[2 0]


In [47]:
var = np.array([[5,8,2,3],[0,6,7,10]])  # Axis =0 "Col", # Axis =1 "Row"
print(np.min(var,axis=0))

[0 6 2 3]


In [48]:
var1 = np.array([4,16,25])
print("Square Root",np.sqrt(var1))

Square Root [2. 4. 5.]


In [49]:
var2 = np.array([1,2,3])

print(np.sin(var2))
print(np.cos(var2))

print(np.cumsum(var2)) # 1, 1+2=3, 3+3=6

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


# Shape and Reshaping in NumPy Arrays

### Shape

In [50]:
var = np.array([[1,2,3,4],[3,4,3,7]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [3 4 3 7]]

(2, 4)


In [51]:
var1 = np.array([1,2,3],ndmin=4)

print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3]]]]

4

(1, 1, 1, 3)


### Reshape

In [52]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [53]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x1 = var3.reshape(2,3,2)

print(x1)
print(x1.ndim)

print()

one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Broadcasting 

In [54]:
var1 =  np.array([1,2,3,4])
var2 =  np.array([1,2,3])

print(var1+var2)  #Must be of Same Dimension

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [55]:
var1 =  np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()

var2 =  np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()
print(var1+var2) 

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing and Slicing

In [56]:
var = np.array([3,4,5,6])

print(var[1])
print(var[-2])

4
5


In [57]:
var1 = np.array([[2,3,4],[5,6,7]])

print(var1)
print(var1.ndim,"- D Array")
print()

print(var1[0,2])

[[2 3 4]
 [5 6 7]]
2 - D Array

4


In [58]:
var2 = np.array([[[1,2],[3,4]]])

print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [3 4]]]
3

4


In [59]:
var = np.array([1,2,3,4,5,6])

print(var[2:6])
print(var[:5])
print(var[5:])
print(var[:])
print(var[::2])
print(var[1:6:2])

[3 4 5 6]
[1 2 3 4 5]
[6]
[1 2 3 4 5 6]
[1 3 5]
[2 4 6]


In [60]:
var1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(var1)
print()

print(var1[2,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[12 13 14 15]


# Iteration

In [61]:
var = np.array([1,2,3,4,5])
print(var)
print()
for i in var:
    print(i)

[1 2 3 4 5]

1
2
3
4
5


In [62]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])

print(var1)
print()

for j in var1:
    print(j)

print()
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [63]:
var3 = np.array([[[1,2,3,4],[5,6,7,8]]])

print(var3)
print()
print(var3.ndim)
print()

for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [5 6 7 8]]]

3

1
2
3
4
5
6
7
8
