## Going to learn about:

1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

In [4]:
import pandas as pd
import numpy as np

In [6]:
np.arange(0,28).reshape(7,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [9]:
# Creating Dataframe
df= pd.DataFrame(data = np.arange(0,28).reshape(7,4), index = ["Row1","Row2","Row3","Row4","Row5","Row6","Row7"], columns = ["Column1","Column2","Column3","Column4"])

In [10]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [11]:
df.tail()

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
Row6       20       21       22       23
Row7       24       25       26       27

In [12]:
df.head(7)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
Row6       20       21       22       23
Row7       24       25       26       27

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Row1 to Row7
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  7 non-null      int32
 1   Column2  7 non-null      int32
 2   Column3  7 non-null      int32
 3   Column4  7 non-null      int32
dtypes: int32(4)
memory usage: 168.0+ bytes


In [15]:
df.describe() # Columns must be integer or float

Column1    Column2    Column3    Column4
count   7.000000   7.000000   7.000000   7.000000
mean   12.000000  13.000000  14.000000  15.000000
std     8.640988   8.640988   8.640988   8.640988
min     0.000000   1.000000   2.000000   3.000000
25%     6.000000   7.000000   8.000000   9.000000
50%    12.000000  13.000000  14.000000  15.000000
75%    18.000000  19.000000  20.000000  21.000000
max    24.000000  25.000000  26.000000  27.000000

## Indexing

- Indexing can be done by these three ways
- Columnname, rowindex[loc], rowindex or columnindex number[.iloc]

In [28]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

- By using column name

In [29]:
# By using column name
df[['Column1','Column2','Column3']] # if you have multiple column then you have to define list in multinested list.

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18
Row6       20       21       22
Row7       24       25       26

In [30]:
type(df[['Column1','Column2','Column3']]) # This is DataFrame

pandas.core.frame.DataFrame

In [31]:
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Row6    20
Row7    24
Name: Column1, dtype: int32

## Series

In [32]:
type(df['Column1']) # This is series

pandas.core.series.Series

- DataFrame is the combination of multiple rows and columns whereas Series is single row or column.

In [33]:
df.loc['Row3']

Column1     8
Column2     9
Column3    10
Column4    11
Name: Row3, dtype: int32

- rowindex[loc]

In [34]:
type(df.loc['Row3'])

pandas.core.series.Series

In [41]:
df.loc[:,['Column1','Column4']]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19
Row6       20       23
Row7       24       27

In [35]:
df.loc[['Row2','Row3']]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11

- rowindex or columnindex number[.iloc]

In [37]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [39]:
df.iloc[1:3,0:2 ] # I need 4 5 8 9

Column1  Column2
Row2        4        5
Row3        8        9

In [40]:
df.iloc[0:5,3:4]

Column4
Row1        3
Row2        7
Row3       11
Row4       15
Row5       19

In [42]:
df.iloc[:,[0,3]]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19
Row6       20       23
Row7       24       27

In [43]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19
Row6       21       22       23
Row7       25       26       27

- Converting dataframe into arrays

In [45]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23],
       [25, 26, 27]])

## Basic Operation

In [48]:
df.isnull().sum() # If the value is not null then it add 0 to it

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [49]:
df1 = pd.DataFrame(data = [[1,np.nan,2],[1,3,4]], index = ["Row1","Row2"], columns = ["Column1","Column2","Column3"])

In [50]:
df1

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [51]:
df1.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [52]:
df1.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [56]:
df1.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [57]:
df["Column1"].value_counts()

0     1
4     1
8     1
12    1
16    1
20    1
24    1
Name: Column1, dtype: int64

In [61]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [63]:
df['Column3'].unique() # Here all the values are unique.

array([ 2,  6, 10, 14, 18, 22, 26])

In [64]:
df >2

Column1  Column2  Column3  Column4
Row1    False    False    False     True
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row5     True     True     True     True
Row6     True     True     True     True
Row7     True     True     True     True

In [67]:
df['Column2']>2

Row1    False
Row2     True
Row3     True
Row4     True
Row5     True
Row6     True
Row7     True
Name: Column2, dtype: bool

In [68]:
df[df['Column2']>2] # Conditional Indexing

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
Row6       20       21       22       23
Row7       24       25       26       27

4. StringIO
5. Pandas read_csv