# Copy VS View

In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4,5])

co = var.copy()
var[1] = 40
print("Var: ",var)
print()
print("Copied data: ",co)

Var:  [ 1 40  3  4  5]

Copied data:  [1 2 3 4 5]


In [3]:
x = np.array([8,9,10,11,12])

vi = x.view()
x[1]=40
print("x: ",x)
print("View: ",vi)

x:  [ 8 40 10 11 12]
View:  [ 8 40 10 11 12]


- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

# Join Array

In [4]:
var1 = np.array([1,2,3,4,5])

var2 = np.array([6,7,8,9,10])


ar = np.concatenate((var1,var2))

print(ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
var1 = np.array([[1,2],[3,4]])

var2 = np.array([[5,6],[7,8]])

ar = np.concatenate((var1,var2), axis =1) # Merging from row side
print(var1)
print()
print(var2)
print()
print(ar)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
var1 = np.array([[1,2],[3,4]])

var2 = np.array([[5,6],[7,8]])

ar = np.concatenate((var1,var2), axis =0) # Column merge
print(var1)
print()
print(var2)
print()
print(ar)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
var_1 = np.array([1,2,3,4,5])

var_2 = np.array([6,7,8,9,10])


ar_new = np.stack((var_1,var_2), axis =1)

print(ar_new)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [8]:
var_1 = np.array([1,2,3,4,5])

var_2 = np.array([6,7,8,9,10])


ar_new1 = np.hstack((var_1,var_2)) #Merging along row
print(ar_new1)
print()
ar_new2 = np.vstack((var_1,var_2)) #Merging along column
print(ar_new2)
print()
ar_new3 = np.dstack((var_1,var_2)) #Merging along height
print(ar_new3)


[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


# Split Array

- Splitting breaks one array into multiple

In [9]:
var = np.array([1,2,3,4,5])

print(var)
ar = np.array_split(var,3)
print()
print(ar)
print()
print(type(ar))
print(ar[0])

[1 2 3 4 5]

[array([1, 2]), array([3, 4]), array([5])]

<class 'list'>
[1 2]


In [10]:
var1 = np.array([[1,2],[3,4],[5,6],[7,8]])

print(var1)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis = 1)
print()
print(ar1)
print()
print(ar2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32)]


# NumPy Arrays Functions

## Search Array

- Search an array for a certain value, and return the indexes that get a match.

In [11]:
var = np.array([1,4,3,4,5,2,6,4,8,2])

x = np.where(var == 2)
x1 = np.where((var % 2) == 0)
print(x)
print()
print(x1)

(array([5, 9], dtype=int64),)

(array([1, 3, 5, 6, 7, 8, 9], dtype=int64),)


In [12]:
var = np.array([1,2,3,4,5,8,9])

x1 = np.searchsorted(var, 7)

print(x1)

5


In [13]:
var = np.array([1,2,3,4,5,8,9])

x1 = np.searchsorted(var, 7,side="right")

print(x1)

5


In [14]:
var = np.array([1,2,3,4,5,8,9])

x1 = np.searchsorted(var, [0,6,7],side="right")

print(x1)

[0 5 5]


# Sort

In [15]:
var = np.array([34,54,12,67,97,11,4])

print(np.sort(var))

[ 4 11 12 34 54 67 97]


In [16]:
var_1 = np.array(["a","d","b"])

print(np.sort(var_1))

['a' 'b' 'd']


In [17]:
var_2 = np.array([[2,6,1],[7,1,2]])

print(np.sort(var_2))

[[1 2 6]
 [1 2 7]]


# Filter Array

- Getting some elements out of an existing array and creating a new array out of them.

In [18]:
var_3 = np.array(["a","d","b","u","n"])

f=[True, True, False, False,True]

new_a = var_3[f]
print(new_a)
print(type(new_a))

['a' 'd' 'n']
<class 'numpy.ndarray'>


# Arithmetic function

In [19]:
var = np.array([1,2,3,4,5])

np.random.shuffle(var)
print(var)

[3 4 1 2 5]


In [20]:
var = np.array([3,4,1,2,4,6,8,5,3])
va=np.unique(var, return_index=True,return_counts=True)
print(va)

(array([1, 2, 3, 4, 5, 6, 8]), array([2, 3, 0, 1, 7, 5, 6], dtype=int64), array([1, 1, 2, 2, 1, 1, 1], dtype=int64))


In [21]:
var2 = np.array([3,1,6,4,3,6])

y = np.resize(var2,(2,3))
print(y)


[[3 1 6]
 [4 3 6]]


- Numpy flatten changes the shape of a Numpy array from a multi-dimensional array, to a 1-dimensional array.

In [22]:
var2 = np.array([3,1,6,4,3,6])

y = np.resize(var2,(2,3))
print(y)
print()
# Order : {'C','F','A','K'}
print("Flatten: ",y.flatten(order = "F")) # By default order ="C"
print()
print("Flatten: ",y.flatten())
print()
print("Ravel: ", np.ravel(y,order="F"))


[[3 1 6]
 [4 3 6]]

Flatten:  [3 4 1 3 6 6]

Flatten:  [3 1 6 4 3 6]

Ravel:  [3 4 1 3 6 6]


- Ravel is faster than flatten() as it does not occupy any memory. Flatten() is comparatively slower than ravel() as it occupies memory. 

# Insert 

In [23]:
var = np.array([1,2,3,4,5,6])

print(var)
print()
v = np.insert(var,0,0) #inserting 0 in 0th index(varname, index,value)
print(v)
print()
v1 = np.insert(var,(3,5),30) #it doesn't accept float values
print(v1)

[1 2 3 4 5 6]

[0 1 2 3 4 5 6]

[ 1  2  3 30  4  5 30  6]


In [24]:
var1 = np.array([[1,2,3],[4,5,6]])

v1 = np.insert(var1,2,7,axis=1)
v2 = np.insert(var1,2,7,axis=0)
print(v1)
print()
print(v2)

[[1 2 7 3]
 [4 5 7 6]]

[[1 2 3]
 [4 5 6]
 [7 7 7]]


In [25]:
var1 = np.array([[1,2,3],[4,5,6]])

v1 = np.insert(var1,2,[7,8,9],axis=0)

print(v1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
var = np.array([1,2,3,4,5])

print(var)

x = np.append(var,6.4)
print(x)

[1 2 3 4 5]
[1.  2.  3.  4.  5.  6.4]


In [27]:
var = np.array([[1,2,3,4],[5,6,7,8]])

print(var)
print()
x = np.append(var,[[9,10,11,12]], axis=0)
print(x)

[[1 2 3 4]
 [5 6 7 8]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Delete

In [28]:
var1 = np.array([1,2,3,4,5])

print(var1)

d = np.delete(var1,2)

print(d)

[1 2 3 4 5]
[1 2 4 5]


# Matrix

In [29]:
var = np.matrix([[1,2,3],[4,5,6]])

print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [30]:
va1 = np.array([[1,2,3],[4,5,6]])

print(var1)
print(type(var1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [31]:
var2 = np.array([[1,2,3],[4,5,6],[2,8,9]])
var3 = np.array([[9,6,4],[1,3,5],[4,3,7]])

print(var2+var3)
print()
print(var2-var3)
print()
print("Array Mul: ")
print(var2*var3)
print()
print("Matrix Mul: ")
print(var3.dot(var2))

[[10  8  7]
 [ 5  8 11]
 [ 6 11 16]]

[[-8 -4 -1]
 [ 3  2  1]
 [-2  5  2]]

Array Mul: 
[[ 9 12 12]
 [ 4 15 30]
 [ 8 24 63]]

Matrix Mul: 
[[41 80 99]
 [23 57 66]
 [30 79 93]]


# Matrix Function

In [32]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()

print(np.transpose(var))
print()
print(var.T)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [33]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [34]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [35]:
var4 = np.matrix([[1,2],[3,4]])

print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

print(np.linalg.matrix_power(var4,0))
print()

print(np.linalg.matrix_power(var4,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [36]:
var5 = np.matrix([[1,2,3],[4,2,7],[7,9,3]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [4 2 7]
 [7 9 3]]

83.00000000000003
